"""initial migration

Revision ID: b19c40b07506
Revises: None
Create Date: 2016-01-05 15:01:27.309561

"""

# revision identifiers, used by Alembic.
revision = 'b19c40b07506'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movieinfo',
    sa.Column('linkmd5id', sa.String(length=32), nullable=False),
    sa.Column('moviesite', sa.String(length=20), server_default=sa.text(u"'NULL'"), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('linkmd5id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movieinfo')
    ### end Alembic commands ###
